### ISSUE TITLE
Showing a badge of list pages

### ISSUE THREAD

**Issue by masutaka** [yurtaev/extension-tweets-favicon-badges#1]
@yurtaev 
Thank you for your good extension!

I would like to show a badge of twitter list pages.
ex. `https://twitter.com/{account}/lists/{list name}`

Can you change like that?

**Comment by yurtaev** [comment]
I pushed new version 0.0.3. it will be available for 60 min.

**Comment by masutaka** [comment]
Greeeeet!!!!
Thanks a lot!!!! :sparkles:

**Comment by masutaka** [comment]
Just posted an article of this extention.
http://masutaka.net/chalow/2016-02-28-1.html (In Jananese)

thanks.
